### ISSUE TITLE
运行infoport.py出现UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 13: illegal multibyte sequence

### ISSUE THREAD

**Issue by 15536818056** [winezer0/RPscan#1]
python infoport.py
```text
[15:47:14] [+] args: {'target': None, 'target_filename': None, 'config_file': '$BASE_DIR$/config.ini', 'ports': 'c2', 'check_alive': 'all', 'port_scan': 'p1,p2,p3,p4', 'service_scan': 's1', 'view_detail_flag': False, 'ignore_ports_flag': False}
[15:47:14] [+] config_file_path: F:\比赛\C4网络技术挑战赛\工具参考\infoport-main/config.ini
Traceback (most recent call last):
  File "infoport.py", line 308, in <module>
    main()
  File "infoport.py", line 286, in main
    init()
  File "infoport.py", line 66, in init
    config_parser.read(config_file_path)
  File "D:\Anaconda3\envs\pytorch\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "D:\Anaconda3\envs\pytorch\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 13: illegal multibyte sequence
```

**Comment by 15536818056** [comment]
> python infoport.py
> 
> ```
> [15:47:14] [+] args: {'target': None, 'target_filename': None, 'config_file': '$BASE_DIR$/config.ini', 'ports': 'c2', 'check_alive': 'all', 'port_scan': 'p1,p2,p3,p4', 'service_scan': 's1', 'view_detail_flag': False, 'ignore_ports_flag': False}
> [15:47:14] [+] config_file_path: F:\比赛\C4网络技术挑战赛\工具参考\infoport-main/config.ini
> Traceback (most recent call last):
>   File "infoport.py", line 308, in <module>
>     main()
>   File "infoport.py", line 286, in main
>     init()
>   File "infoport.py", line 66, in init
>     config_parser.read(config_file_path)
>   File "D:\Anaconda3\envs\pytorch\lib\configparser.py", line 696, in read
>     self._read(fp, filename)
>   File "D:\Anaconda3\envs\pytorch\lib\configparser.py", line 1014, in _read
>     for lineno, line in enumerate(fp, start=1):
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 13: illegal multibyte sequence
> ```

**Comment by 15536818056** [comment]
66行改为  config_parser.read(config_file_path, encoding='utf-8')

**Comment by winezer0** [comment]
感谢您的反馈，已试用简单的文件编码判断模块进行修复 。
1、修改默认配置文件写入编码格式
2、自动判断指定配置文件编码格式
